#!/bin/python
encoding="UTF-8"


# print (5*' ''Sophie')

## Variable
Freundin='Sophie'
Kollegin='Susanne'
# print(Freundin)
# print(Kollegin)
# print(Freundin)+ ' ' +(Kollegin)	#! not working

if zahl > 11
    print('yes')
else zahl < 11
    print("no")
fi
