#!/bin/bash


##########  Test / Todo ##############



#alias zz='exec xfce4-terminal ;  echo termdown 88 ; sleep 1 ; sudo poweroff'
#alias netstat='sudo netstat -tapn |  sed '1 d' | sort -r +6 | grep -v 'TIME_WAIT' | grep -v 'FIN_WAIT' | grep -v 'LISTEN' | grep -v 'CLOSING' | grep -v 'LAST_ACK''
#alias xx='xfce4-terminal --drop-down; exec sleep1 ;cmatric'
######################################
######################################


## Ln Links herstellen
alias backup='ln -fv .zshrc                                $HOME/ownCloud/.bin/dotfile/.zshrc
sudo          ln -fv /etc/lightdm/lightdm.conf             $HOME/ownCloud/.bin/dotfile/lightdm.conf
sudo          ln -fv /etc/vconsole.conf                    $HOME/ownCloud/.bin/dotfile/vconsole.conf
sudo          ln -fv /etc/systemd/journald.conf            $HOME/ownCloud/.bin/dotfile/journald.conf
              ln -fv $HOME/.stignore                           $HOME/ownCloud/.bin/dotfile/.stignore
              sudo pacman -Qqe > $HOME/ownCloud/.bin/dotfile/pkglist.txt'


alias backup-restore='ln -fv $HOME/ownCloud/.bin/dotfile/.zshrc $HOME/.zshrc
sudo ln -fv $HOME/ownCloud/.bin/dotfile/lightdm.conf               /etc/lightdm/lightdm.conf
     ln -fv $HOME/ownCloud/.bin/dotfile/.stignore                $HOME/.stignore 
     sudo ln -fv  $HOME/ownCloud/.bin/dotfile/vconsole.conf /etc/vconsole.conf
     sudo ln -fv  $HOME/ownCloud/.bin/dotfile/journald.conf /etc/journald.conf
sudo timedatectl set-ntp true
sudo systemctl enable --now auto-cpufreq.service
sudo systemctl enable --now NetworkManager
sudo systemctl enable lightdm
sudo mkinitcpio -P && sudo update-grub
sudo journalctl --vacuum-size=33M
sudo find $HOME/.cache/ -type f -atime +88 -delete
sudo find /tmp -type f -atime +10 -delete
sudo systemctl enable --now systemd-timesyncd
sudo fc-cache -vf
'

# alias .config-update='rsync -e'ssh -p 9904' --force -Rravuz --delete-before --exclude gnupg --exclude VirtualBox --exclude Barrier --exclude syncthing --exclude BraveSoftware --exclude .ssh --exclude ownCloud --exclude .stversions --exclude .xsession-errors .config/'   ## 172.20.10.5:

# sudo pacman -Qqe > pkglist.txt
alias pkglist-backup='pacman -Qqe > $HOME/ownCloud/.bin/dotfile/pkglist.txt'
alias pkglist-restore='sudo pacman --needed --noconfirm -Syu && yay --needed --noanswerclean --nocleanmenu --cleanafter --norebuild --batchinstall --combinedupgrade --useask --noredownload --topdown --sudoloop -Syv < $HOME/ownCloud/.bin/dotfile/pkglist.txt'

# yay -Rc -noconfirm --needed pidgin hexchat mousepad xfce4-screensaver samba

## Block any Website
# zb. cat '0.0.0.0 www.pornhub.com' >> /etc/hosts

# Suffix alias
alias -s pdf=xreader
alias -s {jpg,jpeg,png,gif}=ristretto
alias please='sudo !!'
alias cp='cp -vi'                                               # Confirm before overwriting something
alias df='df -h'                                                # Human-readable sizes check
alias free='free -h'                                            # Show sizes in MB
alias np='nano -w PKGBUILD'
alias more='less'
alias pacman-update='sudo pacman-mirrors --fasttrack ; sudo pacman -Syu'
alias update-pacman='sudo pacman-mirrors --fasttrack ; sudo pacman -Syu'
alias errors='sudo systemctl --failed'
alias failed='sudo systemctl --failed'
alias pacman-clean='sudo pacman  -Sc ; /usr/bin/sudo journalctl --vacuum-time=14d ; sudo find /tmp -type f -atime +10 -delete ; sudo find ~/.cache/ -type f -atime +88 -delete ; rm -fr ~/.local/share/Trash/files/* ;ccache -C  '
alias grub-update='sudo mkinitcpio -P && sudo update-grub'
alias ping='ping -c 4'
alias mv='mv -iv' 
alias rm='sudo rm -rfv' 
alias rechner-bc='bc -ql'  								     		#Calculator
alias calculator-bc='bc -ql'  										#Calculator
alias mkdir='mkdir -pv' 
alias yt='youtube-dl --add-metadata -i' 
alias yta='yt -x -f bestaudio/best' 
alias arch-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias ffmpeg='ffmpeg -hide_banner'										 #'ffmpeg -i input.mp4 output.avi'  https:/ffmpeg.org/ffmpeg.html
alias inxi-Fanzy='inxi -Fanzy'                                                   #Info System
alias cubotX30-scrcpy='scrcpy -s X30201010019360 -m 2110 -b 20m'                    #android-screen
alias ip-c='ip -c a'                                                       #ip-coler
alias scp-up='  scp -rv'     #-P9904                                             #scp -P 1234 file user@remote.host:/remote/location/
alias scp-down='scp -rv'     #-P9904                                             #scp -P 1234 user@remote.host:/remote/location/file ./
#manuel alias  rsync-up='rsync -e'ssh   -p9904' --force -Rravuz --delete-before' #pkglist user@remotesystem:/path/           --exclude
# manuel alias  rsync-down='rsync -e'ssh -p9904' --force -Rravuz --delete-before' #pkglist user@remotesystem:/path/
alias ssh-copypub='ssh-copy-id -fi $HOME/.ssh/id_rsa.pub' #-p #IP...                 #man ssh-keygen      #ssh-keygen -t rsa -b 4096
alias defendersca-libredefender='libredefender scan'                             #Linux Antivierus/Defender programm
alias antivirusscan-libredefender='libredefender scan'                           #Linux Antivierus/Defender programm

# Pretty print the path
alias  path='echo $PATH | tr -s ':' '\n''
#alias path='echo -e ${PATH//:/\\n}'

# Network
alias myip='curl http:/ipecho.net/plain; echo'
alias traffic-jnettop='sudo jnettop'
alias nmap='sudo nmap -sS -v'                                                    #nmap -v google.ch  Network Ip scan programm like 
alias traffic-nmap='sudo nmap -sS -v'                                            #nmap -v google.ch  Network Ip scan programm like 
alias networkmanagerlog='journalctl --boot 0 --unit NetworkManager.service --follow'   #NetworkManager info scan

# manuel alias  rsyncvm='rsync -e 'ssh -p9904'  $HOME/VirtualBox\ VMs/ 172.20.10.6:$HOME/VirtualBox\ VMs/ -r --force -avz'
alias wget='wget -c'              							#web get                                                   #Commandline Homepage URL Download > index.html
alias nvim=' nvim'                                                          
alias vim='nvim'
alias n='	 nvim'                                                              
alias env='env'                                                                  #Startup memorie speicher Information  
alias htop='sudo htop'

# rclone
alias drobpox='rclone --attr-timeout 3s         --vfs-cache-mode full    --vfs-read-chunk-size 100M            mount dropbox: $HOME/rclone/dropbox10G              --fast-list'
alias drobpox-encrypt='rclone --attr-timeout 3s --vfs-cache-mode full    --vfs-read-chunk-size 100M            mount dropbox-encrypt: $HOME/rclone/rclone/dropbox-encrypt --fast-list'
alias google-photo='rclone --attr-timeout 3s    --vfs-cache-mode full    --vfs-read-chunk-size 100M            mount google-photo: $HOME/rclone/google-photo       --fast-list                  --allow-non-empty'
alias mega='rclone --attr-timeout 3s            --vfs-cache-mode writes  --vfs-read-chunk-size 100M            mount mega: $HOME/rclone/mega20G                    --fast-list                   --allow-non-empty'
alias mega-eli='rclone --attr-timeout 3s        --vfs-cache-mode full    --vfs-read-chunk-size 100M            mount mega-eli: $HOME/rclone/mega-eli               --fast-list                   --allow-non-empty'
alias mega-crypt='rclone --attr-timeout 3s      --vfs-cache-mode full    --vfs-read-chunk-size 100M            mount mega-crypt: $HOME/rclone/mega-crypt                                         --allow-non-empty'
alias mega-eli-crypt='rclone --attr-timeout 3s  --vfs-cache-mode full    --vfs-read-chunk-size 100M            mount mega-eli-crypt: $HOME/rclone/mega-eli-crypt --allow-non-empty'
alias rschuppisser-onedrive='rclone --attr-timeout 3s --vfs-cache-mode full --vfs-read-chunk-size 100M         mount rschuppisser-onedrive: $HOME/rclone/rschuppisser-onedrive5G                 --allow-non-empty'
alias rschuppisser-onedrive-crypt='rclone --attr-timeout 3s --vfs-cache-mode full --vfs-read-chunk-size 100M   mount rschuppisser-onedrive-crypt: $HOME/rclone/rschuppisser-onedrive-crypt       --allow-non-empty'
alias shaderico-gdrive='rclone --attr-timeout 3s  --vfs-cache-mode full --vfs-read-chunk-size 100M             mount shaderico-gdrive: $HOME/rclone/shaderico-gdrive --fast-list                 --allow-non-empty '
alias shaderico-gdrive-encrypt='rclone --attr-timeout 3s --vfs-cache-mode full --vfs-read-chunk-size 100M      mount shaderico-gdrive-encrypt: $HOME/rclone/shaderico-gdrive-encrypt --fast-list --allow-non-empty'
alias shaderico-gmail-encrypt='rclone --attr-timeout 3s --vfs-cache-mode full --vfs-read-chunk-size 100M       mount shaderico-gmail-encrypt crypt: $HOME/rclone/shaderico-gmail-encrypt crypt   --allow-non-empty'
alias shaderico-gmail='rclone --attr-timeout 3s --vfs-cache-mode full  --vfs-read-chunk-size 100M              mount shaderico-gmail: $HOME/rclone/shaderico-gmail --fast-list                   --allow-non-empty'
alias shaderico-onedrive='rclone --attr-timeout 3s --vfs-cache-mode full --vfs-read-chunk-size 100M            mount shaderico-onedrive: $HOME/rclone/shaderico-onedrive --fast-list             --allow-non-empty'
alias shaderico-onedrive-encrypt='rclone --attr-timeout 3s --vfs-cache-mode full --vfs-read-chunk-size 100M    mount shaderico-onedrive-encrypt: $HOME/rclone/shaderico-onedrive-encrypt         --allow-non-empty'
alias 1Fichier='rclone --attr-timeout 3s        --vfs-cache-mode full  --vfs-read-chunk-size 100M              mount 1Fichier: $HOME/rclone/1Fichier --allow-non-empty       --fast-list         --allow-non-empty'
#alias rclone-owncloud='rclone --attr-timeout 3s --vfs-cache-mode full  --vfs-read-chunk-size 100M              mount rclone-owncloud: $HOME/rclone/rclone-owncloud'

# Colorize commands when possible.
alias ls='ls -thaNr --color=auto --group-directories-first' 
alias ll='ls -thaNrl --color=auto --group-directories-first' 
alias ln='ln -v'
alias grep='grep  --color=auto' 
alias diff='diff  --color=auto' 

# These common commands are just too long! Abbreviate them.
alias ka='killall' 
alias 	e='vscodium' 
alias 	v='$editor' 
alias   p='sudo pacman'
alias  G='| grep'

# Git
alias gu='git update'
alias gitu='git add . && git commit && git push'
alias ga='git add'
alias gp='git push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gcm='git commit -m'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpl='git pull'
alias gcl='git clone'
alias gta='git tag -a -m'
alias gf='git reflog'
alias gdiscard='git checkout -- .'

# Quick/fast access
#alias i='.stignore && $HOME/aliasrc && $HOME/.zshrc' 
alias stignore='e $HOME/.stignore' 
alias zshrc='e $HOME/.zshrc' 
alias aliasrc='e $HOME/aliasrc' 
alias t='mkdir -p ~/Downloads/test && cd ~/Downloads/test && ls'  
alias dl='~/Downloads/ && cd ~/Downloads/ && ls'  
alias cd..='cd .. && ls'
alias ownCloud='$HOME/ownCloud ; ls'
alias D-link='$HOME/ownCloud/D-link ; ls'
alias S-link='$HOME/ownCloud/S-link ; ls'
alias M-link='$HOME/ownCloud/M-link ; ls'
alias W-link='$HOME/ownCloud/W-link ; ls'
alias P-link='$HOME/ownCloud/P-link ; ls'
alias D-link='$HOME/ownCloud/D-link ; ls'

## mount
alias mount='mount |column -t'

## Get server cpu info ##
alias cpuinfo='lscpu'
alias cpuwatch='watch -n 0.5 grep \"cpu MHz\" /proc/cpuinfo'

## get GPU ram on desktop / laptop## 
alias meminfo='grep -i --color memory /var/log/Xorg.0.log'
alias mem-psmc='ps -Ao "comm %cpu %mem"'

#turn screen off
alias screenoff="xset dpms force off"

# sort files in current directory by the number of words they contain
alias wordy='wc -w * | sort | tail -n10'
alias filecount='sudo ls -aRF | wc -l'

#Gets the total disk usage on your machine
alias diskinfo='df -hl --total | grep total'
#alias disk='    df -hTl'

#Gives you what is using the most space. Both directories and files. Varies on current directory
alias most='du -hsx * | sort -rh | head -15'                     # Bigest files in folder
alias bigest-file='du -hsx * | sort -rh | head -15'                     # Bigest files in folder

#shutdown
alias poweroff='termdown 88 ; sleep 1 ; sudo poweroff'      
alias shutdown='termdown 88 ; sleep 1 ; sudo poweroff'    
alias pwf='termdown 88 ; sleep 1 ; sudo poweroff'

